//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAIDANG
    {
        public int BAIDANG_ID { get; set; }
        public string NHANVIEN_ID { get; set; }
        public Nullable<int> DIADIEM_ID { get; set; }
        public Nullable<System.DateTime> BAIDANG_NGAY { get; set; }
        public Nullable<int> BAIDANG_DUYET { get; set; }
        public string BAIDANG_NOIDUNG { get; set; }
    
        public virtual DIADIEM DIADIEM { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
