//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIADIEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIADIEM()
        {
            this.BAIDANGs = new HashSet<BAIDANG>();
            this.TOADOes = new HashSet<TOADO>();
            this.HINHDIADIEMs = new HashSet<HINHDIADIEM>();
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public int DIADIEM_ID { get; set; }
        public string KHACHHANG_ID { get; set; }
        public int LOAI_ID { get; set; }
        public string DIADIEM_TEN { get; set; }
        public string DIADIEM_DIACHI { get; set; }
        public string DIADIEM_WEB { get; set; }
        public string DIADIEM_MOTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAIDANG> BAIDANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOADO> TOADOes { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual LOAI LOAI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HINHDIADIEM> HINHDIADIEMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
