//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINHSANPHAM
    {
        public int HSP_ID { get; set; }
        public int SANPHAM_ID { get; set; }
        public string HSP_LINK { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
