//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.BAIDANGs = new HashSet<BAIDANG>();
        }
    
        public string NHANVIEN_ID { get; set; }
        public string NHANVIEN_TEN { get; set; }
        public Nullable<System.DateTime> NHANVIEN_NGAYSINH { get; set; }
        public string NHANVIEN_DIACHI { get; set; }
        public string NHANVIEN_PHAI { get; set; }
        public string NHANVIEN_EMAIL { get; set; }
        public string NHANVIEN_SDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAIDANG> BAIDANGs { get; set; }
    }
}
