//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.HINHSANPHAMs = new HashSet<HINHSANPHAM>();
        }
    
        public int SANPHAM_ID { get; set; }
        public int DIADIEM_ID { get; set; }
        public string SANPHAM_TEN { get; set; }
        public string SANPHAM_MOTA { get; set; }
        public Nullable<double> SANPHAM_GIA { get; set; }
    
        public virtual DIADIEM DIADIEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HINHSANPHAM> HINHSANPHAMs { get; set; }
    }
}
