//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOADO
    {
        public int TOADO_ID { get; set; }
        public Nullable<double> TOADO_LAT { get; set; }
        public Nullable<double> TOADO_LNG { get; set; }
        public Nullable<int> DIADIEM_ID { get; set; }
    
        public virtual DIADIEM DIADIEM { get; set; }
    }
}
